name: Deploy to production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    environment: production

    env:
      S3_BUCKET: sethsharp.dev
      CLOUDFRONT_DISTRIBUTION_ID: E279RQHWZHC12A

    steps:
      - uses: actions/checkout@v4

      - name: Restore npm cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build nuxt.js application
        run: |
          npm ci
          npm run build

      - name: Generate nuxt.js application
        run: |
          npm run generate

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Deploy to AWS
        run: |
          aws s3 cp .output/public s3://${S3_BUCKET} --recursive --region=ap-southeast-2 --no-progress
          aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths "/*"
